spring:
  application:
    name: backend

  # datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 864000000

tencent:
  cos:
    secretId: ${TENCENT_COS_SECRET_ID}
    secretKey: ${TENCENT_COS_SECRET_KEY}
    bucketName: ${TENCENT_COS_BUCKET_NAME}
    region: ${TENCENT_COS_REGION}
    durationSeconds: ${TENCENT_COS_DURATION_SECONDS}

# server port
server:
  port: 5200
